/** Video registry — set `src` on each entry to publish. Titles are used as labels when clips are active. */

export type VideoLayout = 'vertical' | 'landscape';

export interface VideoSlot {
  id: string;
  title: string;
  aspect: string;
  layout?: VideoLayout;
  category: 'home' | 'events' | 'food' | 'venue';
  src?: string;
}

const videoSrc = (folder: 'home' | 'events' | 'food' | 'venue', fileName: string) =>
  `/assets/videos-optimized/${folder}/${fileName}`;

/** Homepage hero — full-bleed background */
export const homeHeroVideoSlot: VideoSlot = {
  id: 'video-home-hero',
  category: 'home',
  title: 'Main hall celebration',
  aspect: '16:9 · 1920×1080',
  layout: 'landscape',
};

/** Homepage reel — vertical clips */
export const homeReelVideoSlots: VideoSlot[] = [
  {
    id: 'video-home-bride-groom-twirling',
    category: 'events',
    title: 'Bride and groom twirling on the dance floor',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'bride-groom-dance-floor-twirling.mp4'),
  },
  {
    id: 'video-home-spotlight-hall',
    category: 'venue',
    title: 'Black, gold, and white hall setup with spotlights',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-gold-white-spotlight-tables.mp4'),
  },
  {
    id: 'video-home-storybook-celebration',
    category: 'events',
    title: 'Storybook-themed celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'storybook-themed-celebration.mp4'),
  },
  {
    id: 'video-home-fresh-indian-buffet',
    category: 'food',
    title: 'Fresh Indian dinner buffet',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'fresh-indian-dinner-buffet-display.mp4'),
  },
  {
    id: 'video-home-dessert-room',
    category: 'food',
    title: 'Dessert room and sweet table',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-room-sweet-table.mp4'),
  },
  {
    id: 'video-home-white-gold-walkthrough',
    category: 'venue',
    title: 'Walking into a white and gold hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'walking-into-simple-white-gold.mp4'),
  },
  {
    id: 'video-home-reel-01',
    category: 'events',
    title: 'Indian reception setup and celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'indian-reception-showcase.mp4'),
  },
  {
    id: 'video-home-reel-02',
    category: 'events',
    title: 'Indian reception celebration in the main hall',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'indian-reception-celebration.mp4'),
  },
  {
    id: 'video-home-reel-03',
    category: 'events',
    title: 'Sparkler entrance onto the dance floor',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'dancefloor-sparklers-entry.mp4'),
  },
  {
    id: 'video-home-reel-04',
    category: 'food',
    title: 'Indian buffet walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'indian-buffet-walkthrough.mp4'),
  },
  {
    id: 'video-home-reel-05',
    category: 'venue',
    title: 'Lobby appetizer service',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'lobby-appetizer-service.mp4'),
  },
  {
    id: 'video-home-reel-06',
    category: 'venue',
    title: 'Stage and loveseat setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('home', 'stage-loveseat-setup.mp4'),
  },
];

/** Events — gallery, events hub, home */
export const eventVideoSlots: VideoSlot[] = [
  {
    id: 'video-event-bride-groom-twirling',
    category: 'events',
    title: 'Bride and groom twirling on the dance floor',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'bride-groom-dance-floor-twirling.mp4'),
  },
  {
    id: 'video-event-storybook-celebration',
    category: 'events',
    title: 'Storybook-themed celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'storybook-themed-celebration.mp4'),
  },
  {
    id: 'video-event-wedding-ceremony-chair-setup',
    category: 'events',
    title: 'Wedding ceremony chair setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'wedding-ceremony-chair-setup.mp4'),
  },
  {
    id: 'video-event-wedding-sparklers',
    category: 'events',
    title: 'Wedding dance with smoke and sparklers',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'wedding-smoke-sparklers-dance.mp4'),
  },
  {
    id: 'video-event-wedding-dancefloor',
    category: 'events',
    title: 'Wedding dance floor celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'wedding-dance-floor-celebration.mp4'),
  },
  {
    id: 'video-event-sparkler-entry',
    category: 'events',
    title: 'Sparkler entrance onto the dance floor',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dancefloor-sparklers-entry.mp4'),
  },
  {
    id: 'video-event-dancefloor-lighting',
    category: 'events',
    title: 'Dance floor lighting and crowd energy',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dancefloor-lighting.mp4'),
  },
  {
    id: 'video-event-dancefloor-train',
    category: 'events',
    title: 'Close-up dance floor train',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dancefloor-train-closeup.mp4'),
  },
  {
    id: 'video-event-dancefloor-lift',
    category: 'events',
    title: 'Dance floor shoulder lift celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dancefloor-shoulder-lift.mp4'),
  },
  {
    id: 'video-event-group-celebration',
    category: 'events',
    title: 'Group celebration on the dance floor',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dance-floor-group-celebration.mp4'),
  },
  {
    id: 'video-event-performance',
    category: 'events',
    title: 'Reception performance entrance',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'reception-performance-entrance.mp4'),
  },
  {
    id: 'video-event-indian-party',
    category: 'events',
    title: 'Indian reception celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'indian-reception-celebration.mp4'),
  },
  {
    id: 'video-event-reception-setup',
    category: 'events',
    title: 'Indian reception setup showcase',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'indian-reception-setup-showcase.mp4'),
  },
  {
    id: 'video-event-reception-party',
    category: 'events',
    title: 'Indian reception setup and celebration',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'indian-reception-setup-celebration.mp4'),
  },
  {
    id: 'video-event-stage-setup',
    category: 'events',
    title: 'Stage and loveseat setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'stage-loveseat-setup.mp4'),
  },
  {
    id: 'video-event-stage-wide',
    category: 'events',
    title: 'Wide stage and loveseat view',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'stage-loveseat-wide.mp4'),
  },
  {
    id: 'video-event-photobooth-guests',
    category: 'events',
    title: 'Photobooth guests with props',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'photobooth-guests-with-props.mp4'),
  },
  {
    id: 'video-event-photobooth-table',
    category: 'events',
    title: 'Photobooth prop table',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'photobooth-prop-table.mp4'),
  },
  {
    id: 'video-event-dj',
    category: 'events',
    title: 'DJ booth and event lighting',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'dj-booth.mp4'),
  },
  {
    id: 'video-event-musician',
    category: 'events',
    title: 'String instrument performer',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'string-instrument-performer.mp4'),
  },
  {
    id: 'video-event-aerial-service',
    category: 'events',
    title: 'Aerial drink service moment',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'aerial-drink-service.mp4'),
  },
  {
    id: 'video-event-bartenders',
    category: 'events',
    title: 'Bartenders mixing drinks in the lobby',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('events', 'lobby-bartenders-mixing.mp4'),
  },
];

/** Venue walkthrough — dedicated clips per space */
export const venueVideoSlots: VideoSlot[] = [
  {
    id: 'video-venue-spotlight-tables',
    category: 'venue',
    title: 'Black, gold, and white hall setup with spotlights',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-gold-white-spotlight-tables.mp4'),
  },
  {
    id: 'video-venue-black-gold-lighting-setup',
    category: 'venue',
    title: 'Black and gold hall lighting setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-gold-hall-lighting-setup.mp4'),
  },
  {
    id: 'video-venue-black-gold',
    category: 'venue',
    title: 'Black and gold hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-and-gold-hall-setup.mp4'),
  },
  {
    id: 'video-venue-white-gold-walkthrough',
    category: 'venue',
    title: 'Walking into a white and gold hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'walking-into-simple-white-gold.mp4'),
  },
  {
    id: 'video-venue-black-gold-white-overview',
    category: 'venue',
    title: 'Black, gold, and white hall overview',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-gold-white-hall-overview.mp4'),
  },
  {
    id: 'video-venue-black-green',
    category: 'venue',
    title: 'Black and green hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-and-green-setup.mp4'),
  },
  {
    id: 'video-venue-simple-white-gold',
    category: 'venue',
    title: 'Simple white and gold hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'simple-white-gold-hall-setup.mp4'),
  },
  {
    id: 'video-venue-center-hall-chairs',
    category: 'venue',
    title: 'Black, white, and gold chair setup from center hall',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'black-white-gold-chairs-center-hall.mp4'),
  },
  {
    id: 'video-venue-hall-setup-montage',
    category: 'venue',
    title: 'Hall setup montage',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'hall-setup-montage.mp4'),
  },
  {
    id: 'video-venue-walkthrough-lighting-setup',
    category: 'venue',
    title: 'Walking into a hall setup with event lighting',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'walking-into-hall-lighting-setup.mp4'),
  },
  {
    id: 'video-venue-arrival',
    category: 'venue',
    title: 'Walking into the hall as guests arrive',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'walking-into-hall-guests-arriving.mp4'),
  },
  {
    id: 'video-venue-hall-overview',
    category: 'venue',
    title: 'Hall overview from an elevated view',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'hall-overview-elevated-view.mp4'),
  },
  {
    id: 'video-venue-hall-setup',
    category: 'venue',
    title: 'Hall stage setup pan',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'hall-stage-setup-pan.mp4'),
  },
  {
    id: 'video-venue-hall-room',
    category: 'venue',
    title: 'Another completed hall setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'hall-setup-overview.mp4'),
  },
  {
    id: 'video-venue-stage',
    category: 'venue',
    title: 'Stage and loveseat setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'stage-loveseat-setup.mp4'),
  },
  {
    id: 'video-venue-stage-wide',
    category: 'venue',
    title: 'Wide stage and loveseat view',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'stage-loveseat-wide.mp4'),
  },
  {
    id: 'video-venue-lobby-guests',
    category: 'venue',
    title: 'Full lobby with guests mingling',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'lobby-guests-mingling.mp4'),
  },
  {
    id: 'video-venue-lobby-service',
    category: 'venue',
    title: 'Lobby appetizer service',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'lobby-appetizer-service.mp4'),
  },
  {
    id: 'video-venue-main-bar',
    category: 'venue',
    title: 'Main bar service moment',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'main-bar-service-moment.mp4'),
  },
  {
    id: 'video-venue-lobby-bar',
    category: 'venue',
    title: 'Lobby bartenders mixing drinks',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'lobby-bartenders-mixing.mp4'),
  },
  {
    id: 'video-venue-drinks',
    category: 'venue',
    title: 'Bartender pouring drinks in the lobby',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'lobby-bartender-pouring-drinks.mp4'),
  },
  {
    id: 'video-venue-photobooth',
    category: 'venue',
    title: 'Photobooth prop table',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('venue', 'photobooth-prop-table.mp4'),
  },
];

/** Food & catering */
export const foodVideoSlots: VideoSlot[] = [
  {
    id: 'video-food-coffee-bar-buffet',
    category: 'food',
    title: 'Coffee bar and buffet walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'coffee-bar-buffet-walkthrough.mp4'),
  },
  {
    id: 'video-food-indian-appetizer-bar',
    category: 'food',
    title: 'Indian appetizer bar',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'indian-appetizer-bar.mp4'),
  },
  {
    id: 'video-food-ice-cream-sweet-station',
    category: 'food',
    title: 'Ice cream and sweet station walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'ice-cream-sweet-station-walkthrough.mp4'),
  },
  {
    id: 'video-food-dessert-room',
    category: 'food',
    title: 'Dessert room and sweet table',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-room-sweet-table.mp4'),
  },
  {
    id: 'video-food-bread-assortment',
    category: 'food',
    title: 'Bread assortment display',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'bread-assortment.mp4'),
  },
  {
    id: 'video-food-fresh-indian-buffet-display',
    category: 'food',
    title: 'Fresh Indian dinner buffet',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'fresh-indian-dinner-buffet-display.mp4'),
  },
  {
    id: 'video-food-salad-bar-setup',
    category: 'food',
    title: 'Salad bar setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'salad-bar-setup.mp4'),
  },
  {
    id: 'video-food-antipasto-room',
    category: 'food',
    title: 'Antipasto bar room walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'antipasto-bar-room-walkthrough.mp4'),
  },
  {
    id: 'video-food-antipasto-bar',
    category: 'food',
    title: 'Antipasto bar walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'antipasto-bar-walkthrough.mp4'),
  },
  {
    id: 'video-food-antipasto-additional',
    category: 'food',
    title: 'Antipasto bar additional items',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'antipasto-bar-additional-items.mp4'),
  },
  {
    id: 'video-food-italian-buffet',
    category: 'food',
    title: 'Italian buffet walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'italian-buffet-walkthrough.mp4'),
  },
  {
    id: 'video-food-shrimp-flambee',
    category: 'food',
    title: 'Shrimp flambee station',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'shrimp-flambee.mp4'),
  },
  {
    id: 'video-food-pav-bhaji',
    category: 'food',
    title: 'Pav bhaji live station',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'pav-bhaji-live-station.mp4'),
  },
  {
    id: 'video-food-dessert-cake',
    category: 'food',
    title: 'Dessert and cake setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-cake-setup.mp4'),
  },
  {
    id: 'video-food-buffet-pan',
    category: 'food',
    title: 'Indian buffet pan',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'indian-buffet-pan.mp4'),
  },
  {
    id: 'video-food-salad-bar',
    category: 'food',
    title: 'Salad bar walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'salad-bar-walkthrough.mp4'),
  },
  {
    id: 'video-food-fresh-buffet',
    category: 'food',
    title: 'Fresh Indian dinner buffet',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'fresh-indian-dinner-buffet.mp4'),
  },
  {
    id: 'video-food-pizza',
    category: 'food',
    title: 'Midnight pizza station',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'midnight-pizza-station.mp4'),
  },
  {
    id: 'video-food-buffet-guests',
    category: 'food',
    title: 'Buffet walkthrough while guests are served',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'indian-buffet-guests-serving.mp4'),
  },
  {
    id: 'video-food-dinner-walkthrough',
    category: 'food',
    title: 'Indian dinner buffet walkthrough',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'indian-dinner-buffet-walkthrough.mp4'),
  },
  {
    id: 'video-food-dessert-setup',
    category: 'food',
    title: 'Dessert table setup',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-table-setup.mp4'),
  },
  {
    id: 'video-food-dessert-display',
    category: 'food',
    title: 'Dessert table display',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-table-display.mp4'),
  },
  {
    id: 'video-food-dessert-overview',
    category: 'food',
    title: 'Dessert table overview',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-table-overview.mp4'),
  },
  {
    id: 'video-food-dessert-closeup',
    category: 'food',
    title: 'Dessert display close-up',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'dessert-display-closeup.mp4'),
  },
  {
    id: 'video-food-sweet-desserts',
    category: 'food',
    title: 'Sweet dessert selection',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'sweet-desserts.mp4'),
  },
  {
    id: 'video-food-appetizers',
    category: 'food',
    title: 'Lobby appetizer service',
    aspect: '9:16 vertical · MP4',
    layout: 'vertical',
    src: videoSrc('food', 'lobby-appetizer-service.mp4'),
  },
];

export const videoShotList: { page: string; slots: VideoSlot[] }[] = [
  { page: 'Home — hero background', slots: [homeHeroVideoSlot] },
  { page: 'Home — reel carousel', slots: homeReelVideoSlots },
  { page: 'Events / Gallery — event reel', slots: eventVideoSlots },
  { page: 'Venue — walkthrough reel', slots: venueVideoSlots },
  { page: 'Gallery / Menus — food reel', slots: foodVideoSlots },
];
